openapi: 3.0.0
info:
  version: 1.0.0
  title: Example API
  description: >-
    An example API that demonstrates REST-api implementation best practice in
    Brønnøysundregistrene
  contact:
    name: Informasjonsforvaltning API Team
  license:
    name: Norsk lisens for offentlige data (NLOD) 2.0
    url: https://data.norge.no/nlod/no/2.0
paths:
  /industrialcodes:
    get:
      description: Returns all industrial codes from the system that the user has access to
      responses:
        '200':
          description: A list of industrial codes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/industrialcode'
    post:
      summary: Create an industrial code
      operationId: createIndustrialcodes
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - industrialcode
                - description
              properties:
                industrialcode:
                  type: string
                description:
                  type: string
        description: The industrial code to create
  '/industrialcodes/{id}':
    get:
      description: >-
        Returns an industrial code with the given id from the system that the
        user has access to
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the industrial code to retrieve
          schema:
            type: string
      responses:
        '200':
          description: An industrial code with the given id.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/industrialcode'
    put:
      summary: Update an industrial code
      operationId: updateIndustrialcode
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the industrial code to update
          schema:
            type: string
      responses:
        '204':
          description: Updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - industrialcode
                - description
              properties:
                industrialcode:
                  type: string
                description:
                  type: string
        description: The industrial code to update
    delete:
      description: deletes a single industrial code based on the ID supplied
      operationId: deleteIndustrialcode
      parameters:
        - name: id
          in: path
          description: ID of industrial code to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: industrial code deleted
servers:
  - url: 'http://localhost:8080/'
components:
  schemas:
    industrialcode:
      type: object
      required:
        - id
        - industrialcode
        - description
      properties:
        id:
          type: integer
          format: int64
        industrialcode:
          type: string
        description:
          type: string
