openapi: 3.0.2
info:
  version: 1.0.0
  title: Example API
  description: >-
    An example API that demonstrates REST-api implementation best practice in
    Brønnøysundregistrene
  contact:
    name: Informasjonsforvaltning API Team
  license:
    name: Norsk lisens for offentlige data (NLOD) 2.0
    url: https://data.norge.no/nlod/no/2.0
tags:
  - name: api
  - name: industrialcode
  - name: slash
servers:
  - url: http://localhost:8080/api/industrialcodes
    description: Development server
paths:
  /:
    get:
      description: Returns all industrial codes from the system that the user has access to
      operationId: listIndustrialcodes
      tags:
        - industrialcode
      responses:
        '200':
          description: A list of industrial codes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/industrialcode'
    post:
      description: Create an industrial code
      operationId: createIndustrialcodes
      tags:
        - industrialcode
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - industrialcode
                - description
              properties:
                industrialcode:
                  type: string
                description:
                  type: string
        description: The industrial code to create
  '/{id}':
    get:
      description: >-
        Returns an industrial code with the given id from the system that the
        user has access to
      operationId: getIndustrialcode
      tags:
        - industrialcode
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the industrial code to retrieve
          schema:
            type: number
            example: 1
      responses:
        '200':
          description: An industrial code with the given id.
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/industrialcode'
    put:
      description: Update an industrial code
      operationId: updateIndustrialcode
      tags:
        - industrialcode
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the industrial code to update
          schema:
            type: number
            default: 1
      responses:
        '204':
          description: Updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - industrialcode
                - description
              properties:
                industrialcode:
                  type: string
                description:
                  type: string
        description: The industrial code to update
    delete:
      description: deletes a single industrial code based on the ID supplied
      operationId: deleteIndustrialcode
      tags:
        - industrialcode
      parameters:
        - name: id
          in: path
          description: ID of industrial code to delete
          required: true
          schema:
            type: number
            default: 1
      responses:
        '204':
          description: industrial code deleted
components:
  schemas:
    industrialcode:
      type: object
      required:
        - id
        - industrialcode
        - description
      properties:
        id:
          type: number
          example: 1
        industrialcode:
          type: string
          example: "01.120"
        description:
          type: string
          example: Dyrking av ris
