---
  OpenAPI: "2.0"
  info:
    version: "1.0.0"
    title: "Example API"
    description: "An example API that demonstrates REST-api implementation best practice in Brønnøysundregistrene"
    termsOfService: "http://swagger.io/terms/"
    contact:
      name: "Informasjonsforvaltning API Team"
    license:
      name: "MIT"
  host: "localhost:8080"
  basePath: ""
  schemes:
    - "http"
  consumes:
    - "application/json"
  produces:
    - "application/json"
  paths:
    /pets:
      get:
        description: "Returns all pets from the system that the user has access to"
        produces:
          - "application/json"
        responses:
          "200":
            description: "A list of pets."
            schema:
              type: "array"
              items:
                $ref: "#/definitions/Pet"
    /pets/{petId}:
      get:
        description: "Returns a pet with the given id from the system that the user has access to"
        parameters:
              - name: petId
                in: path
                required: true
                description: The id of the pet to retrieve
                type: string
        produces:
          - "application/json"
        responses:
          "200":
            description: "A pet with the given id."
            schema:
              type: "object"
              items:
                $ref: "#/definitions/Pet"

  definitions:
    Pet:
      type: "object"
      required:
        - "id"
        - "name"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        tag:
          type: "string"
